### PR TITLE
feat: change subprojects to modules

### PR DESCRIPTION
**Pull request by wyu71**
change subprojects to modules

Log: change subprojects to modules

### CODE REVIEW

**Comment by Groveer** [comment]
3rdparty 源码应该放在src目录

**Comment by wyu71** [comment]
> 3rdparty 源码应放于src目录

已将3rdparty 源码应放于src目录

**Comment by toberyan** [comment]
为何会有include/dtkdevice这类格式的目录

**Comment by wyu71** [comment]
> 为何会有include/dtkdevice这类格式的目录

image
仿照dtk的定义的

**Comment by toberyan** [comment]
+1

**Comment by Groveer** [comment]
+1

**Review by toberyan — APPROVED** [review]

**Pull request merged**
